server {
    server_name api.26studio.ru;

    location / {
        proxy_pass http://127.0.0.1:3000; # порт твоего backend-а
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    listen 80;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/api.26studio.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.26studio.ru/privkey.pem;
}
