services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=studio26
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./server
    restart: always
    environment:
      - PORT=3000
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=studio26
      - DB_HOST=postgres
      - DB_PORT=5432
      - CLIENTURL=https://26studio.ru
    expose:
      - "3000"
    depends_on:
      - postgres
    volumes:
      - my_app_data:/app/static
      - my_app_data:/app/extracted
      - my_app_data:/app/uploads

  frontend:
    build: ./client
    restart: always
    expose:
      - "80"

  caddy:
    image: caddy:2.7
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  my_app_data:
  pg_data:
  caddy_data:
  caddy_config:
