version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=studio26
    ports:
      - 5432:5432

  backend:
    build: ./server
    ports:
      - 3000:3000
    restart: always
    environment:
      - PORT=3000
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=studio26
      - DB_HOST=postgres
      - DB_PORT=5432
      - CLIENTURL=https://26studio.ru
    depends_on:
      - postgres
      - frontend
    volumes:
      - my_app_data:/app/static
      - my_app_data:/app/extracted
      - my_app_data:/app/uploads

  frontend:
    build: ./client
    ports:
      - 80:80
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token eyJhIjoiMWYwNDMwYWViNGMwM2QzZjRkNTc4OWUzMjFjYjI2MzAiLCJ0IjoiNmM0YmNhMzctMTJkMS00MjQzLTg1N2ItYWRlNDZhMjM5YzU3IiwicyI6Ik9XRXhOalUyTlRZdE5tTm1aaTAwWlRBd0xUbGpObU10T1dWa1ptVXhNek5rTmpVeiJ9
    restart: always
    depends_on:
      - backend
      - frontend
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml

volumes:
  my_app_data:
