version: '3'

services:
  postgres:
    image: postgres:13.14-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=studio26
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  backend:
    build: ./server
    ports:
      - 3000:3000
    restart: always
    environment:
      - PORT=5000
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=studio26
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
      - frontend
  frontend:
    build: ./client
    ports:
      - 80:80
    restart: always
    environment:
      - APP_API_URL=http://backend:6000
